#! /bin/sh
# 1. Arrange Screens
xrandr --output eDP-1 --auto --primary --output HDMI-1 --auto --above eDP-1

# 2. Assign Desktops
bspc monitor HDMI-1 -d 1 2 3 4 5
bspc monitor eDP-1 -d 6 7 8 9 10

# 3. Global Config
bspc config border_width          2
bspc config window_gap           12
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true

# 4. Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# this is needed PCManFM so that it can see mounted devices
/usr/libexec/gvfsd &
/usr/libexec/polkit-gnome-authentication-agent-1 &

# 5. Background Services
# Start PulseAudio for sound
# pulseaudio --start &

# Kill any failed attempts first
pkill -9 pulseaudio || true

# Start the PipeWire stack
pipewire &
sleep 1
pipewire-pulse &
sleep 1
wireplumber &
# Set Wallpaper (added & so it doesn't block)
feh --bg-fill /home/zaky/Pictures/motorcycle_restaurant.jpg &

# Start Hotkey Daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Launch Polybar (added & so it doesn't block)
$HOME/.config/polybar/launch.sh &